Repository jenkinsci/credentials-plugin, pull requests merged in 2020-07, with the labels that each got.

#157 Fix runtime error from type erasure
  src/main/java/com/cloudbees/plugins/credentials/GlobalCredentialsConfiguration.java
  src/main/resources/com/cloudbees/plugins/credentials/GlobalCredentialsConfiguration/index.jelly
Labels: internal

#151 Updated example for correct method call
  docs/consumer.adoc
Labels: documentation

#158 Another IllegalArgumentException from SecretBytes in 2.235.x, this time fromString
  src/main/java/com/cloudbees/plugins/credentials/SecretBytes.java
  src/test/java/com/cloudbees/plugins/credentials/SecretBytesTest.java
Labels: bug

#163 Replace esclave with agent in credentials plug-in (fr)
  src/main/resources/com/cloudbees/plugins/credentials/Messages_fr.properties
Labels: documentation
