Repository jenkinsci/credentials-plugin, pull requests merged in 2022-01, with the labels that each got.

#266 [JENKINS-67132] Default `UsernamePasswordCredentialsImpl.usernameSecret` without `readResolve`
  src/main/java/com/cloudbees/plugins/credentials/impl/UsernamePasswordCredentialsImpl.java
  src/test/java/com/cloudbees/plugins/credentials/impl/UsernamePasswordCredentialsImplTest.java
Labels: bug

#269 Simplify POM
  pom.xml
Labels: chore

#272 Bump parent POM
  pom.xml
  src/test/java/com/cloudbees/plugins/credentials/impl/BaseStandardCredentialsTest.java
Labels: dependencies

#248 Refer to icons using classes instead of filenames
  src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/CredentialsWrapper/sidepanel.jelly
  src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/DomainWrapper/index.jelly
  src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/DomainWrapper/sidepanel.jelly
  src/main/webapp/images/credential.svg
  src/main/webapp/images/credentials.svg
  src/main/webapp/images/folder-store.svg
  src/main/webapp/images/move.svg
  src/main/webapp/images/new-credential.svg
  src/main/webapp/images/new-domain.svg
  src/main/webapp/images/system-store.svg
  src/main/webapp/images/user-store.svg
Labels: enhancement
