Repository jenkinsci/credentials-plugin, pull requests merged in 2023-10, with the labels that each got.

#410 [JENKINS-52386] Add preview for markup of a CredentialParameterDefinition
  src/main/resources/com/cloudbees/plugins/credentials/CredentialsParameterDefinition/config.jelly
Labels: enhancement

#488 Use `Descriptor.bindJSON` to support complex describable fields in custom credentials
  src/main/java/com/cloudbees/plugins/credentials/CredentialsSelectHelper.java
  src/main/java/com/cloudbees/plugins/credentials/CredentialsStoreAction.java
Labels: developer

#481 Do not use `FormApply#applyResponse` to execute arbitrary javascript
  src/main/java/com/cloudbees/plugins/credentials/CredentialsSelectHelper.java
  src/main/resources/lib/credentials/select/select.js
  src/test/java/com/cloudbees/plugins/credentials/CredentialsSelectHelperTest.java
  src/test/resources/com/cloudbees/plugins/credentials/CredentialsSelectHelperTest/CredentialsSelectionAction/index.jelly
Labels: chore

#491 Prepare for prototype removal
  src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/newDomain.jelly
  src/main/resources/lib/credentials/dialog.js
Labels: chore

#490 [JEP-227][JENKINS-39324] Replace Acegi Security with Spring Security APIs
  docs/consumer.adoc
  docs/implementation.adoc
  src/main/java/com/cloudbees/plugins/credentials/CredentialsParameterDefinition.java
  src/main/java/com/cloudbees/plugins/credentials/CredentialsParameterValue.java
  src/main/java/com/cloudbees/plugins/credentials/CredentialsProvider.java
  src/main/java/com/cloudbees/plugins/credentials/CredentialsStore.java
  src/main/java/com/cloudbees/plugins/credentials/CredentialsStoreAction.java
  src/main/java/com/cloudbees/plugins/credentials/SystemCredentialsProvider.java
  src/main/java/com/cloudbees/plugins/credentials/UserCredentialsProvider.java
  src/main/java/com/cloudbees/plugins/credentials/ViewCredentialsAction.java
  src/main/java/com/cloudbees/plugins/credentials/common/AbstractIdCredentialsListBoxModel.java
  src/test/java/com/cloudbees/plugins/credentials/CredentialsProviderTest.java
  src/test/java/com/cloudbees/plugins/credentials/CredentialsUnavailableExceptionTest.java
  src/test/java/com/cloudbees/plugins/credentials/MockFolderCredentialsProvider.java
  src/test/java/com/cloudbees/plugins/credentials/casc/CredentialsProviderTest.java
  src/test/java/com/cloudbees/plugins/credentials/casc/SystemCredentialsTest.java
  src/test/java/com/cloudbees/plugins/credentials/domains/DomainRestrictedCredentialsTest.java
  src/test/java/com/cloudbees/plugins/credentials/domains/DomainTest.java
  src/test/java/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImplTest.java
Labels: developer

#492 Compatibility error in `CredentialsProvider`
  src/main/java/com/cloudbees/plugins/credentials/CredentialsProvider.java
  src/main/java/com/cloudbees/plugins/credentials/CredentialsStore.java
Labels: bug
