Repository jenkinsci/credentials-plugin, pull requests merged in 2024-10, with the labels that each got.

#533 CSP compatibility improvements
  src/main/java/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImpl.java
  src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/CredentialsWrapper/update.jelly
  src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/DomainWrapper/configure.jelly
  src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/DomainWrapper/newCredentials.jelly
  src/main/resources/com/cloudbees/plugins/credentials/CredentialsStoreAction/newDomain.jelly
  src/main/resources/com/cloudbees/plugins/credentials/GlobalCredentialsConfiguration/index.jelly
  src/main/resources/com/cloudbees/plugins/credentials/common/formBehaviour.js
  src/main/resources/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImpl/UploadedKeyStoreSource/config.jelly
  src/main/resources/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImpl/UploadedKeyStoreSource/configUpload.js
  src/main/resources/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImpl/credentials.jelly
  src/main/resources/lib/credentials/select.jelly
  src/main/resources/lib/credentials/select/select.css
  src/main/resources/lib/credentials/select/select.js
  src/test/java/com/cloudbees/plugins/credentials/impl/CertificateCredentialsImplTest.java
Labels: enhancement

#551 Update 'Add credentials' dropdown button
  pom.xml
  src/main/resources/lib/credentials/select.jelly
  src/main/resources/lib/credentials/select/select.js
  src/test/java/com/cloudbees/plugins/credentials/CredentialsSelectHelperTest.java
Labels: enhancement

#566 Require Java 17 or newer; migrate to EE 9
  Jenkinsfile
  pom.xml
  src/main/java/com/cloudbees/plugins/credentials/ContextInPath.java
  src/main/java/com/cloudbees/plugins/credentials/ContextMenuIconUtils.java
  src/main/java/com/cloudbees/plugins/credentials/CredentialsDescriptor.java
  src/main/java/com/cloudbees/plugins/credentials/CredentialsNameComparator.java
  src/main/java/com/cloudbees/plugins/credentials/CredentialsParameterDefinition.java
  src/main/java/com/cloudbees/plugins/credentials/CredentialsParameterValue.java
  src/main/java/com/cloudbees/plugins/credentials/CredentialsProvider.java
  src/main/java/com/cloudbees/plugins/credentials/CredentialsProviderManager.java
  src/main/java/com/cloudbees/plugins/credentials/CredentialsSelectHelper.java
  src/main/java/com/cloudbees/plugins/credentials/CredentialsStore.java
  src/main/java/com/cloudbees/plugins/credentials/CredentialsStoreAction.java
  src/main/java/com/cloudbees/plugins/credentials/GlobalCredentialsConfiguration.java
  src/main/java/com/cloudbees/plugins/credentials/UserCredentialsProvider.java
  src/main/java/com/cloudbees/plugins/credentials/ViewCredentialsAction.java
  src/test/java/com/cloudbees/plugins/credentials/CredentialsStoreActionTest.java
Labels: internal

#557 Adding credentials should not require a check on CredentialsStore#isDomainsModifiable
  src/main/java/com/cloudbees/plugins/credentials/CredentialsSelectHelper.java
Labels: bug

#571 Require 2.479.1 LTS or newer
  pom.xml
Labels: skip-changelog
